### ISSUE TITLE
Rails 6 compatibility

### ISSUE THREAD

**Issue by tjwallace** [jhollinger/occams-record#3]
Not sure what, if anything, needs to be done, but it would be great to have this gem support Rails 6. Thanks!

**Comment by jhollinger** [comment]
I don't believe Rails 6 is out yet, but I'll start looking at what's changed.

**Comment by jhollinger** [comment]
So this might be easier than I expected. I plan to have support in 1.1.0, but it's looking fine in 1.1.0.beta1 already. Give that a try and post any issues here. Thanks.

**Comment by tjwallace** [comment]
Thanks @jhollinger. There are a few more gems in our app that need to be Rails 6 compatible before we can start fully testing. I'll update here when we get there.

**Comment by tjwallace** [comment]
@jhollinger I managed to get the rest of our app's gems updated to support Rails 6 and I'm not seeing any issues with version `1.1.0.beta1`. Thanks 👍

**Comment by jhollinger** [comment]
Great, glad to hear it. I fixed some (very minor) bugs, so you may want to upgrade to `1.1.0.beta2`. Thanks for the feedback

**Comment by jhollinger** [comment]
Closing issue; 1.1.0 went out on June 29th with Active Record 6 support.
