### ISSUE TITLE
GitHub Page doesn’t include link to repo

### ISSUE THREAD

**Issue by ttilberg** [jhollinger/occams-record#6]
Hi, just a small note: I landed on the [GitHub Page](https://jhollinger.github.io/occams-record/) and wasn’t able to find a quick link to the GitHub repo. I was on mobile and wanted to star the gem for later. I ended up cracking a new tab to search for the gem. Right, I know. First world problem. But, I just wanted to share it with you as it’s easy enough, and it might help other users get on their way. 

Cool gem, thanks!

**Comment by jhollinger** [comment]
Just added a link to the main body. Thanks for the note!
